language: rust
rust: stable
env:
  global:
    - TARGET_BUILD=thumbv7em-none-eabi
    - RUSTFLAGS="--deny warnings"

install:
  - rustup target add $TARGET_BUILD
  - rustup component add rustfmt

stages:
  - test
  - name: deploy
    if: branch = master AND type = push

jobs:
  include:
    - stage: test
      script: ci/test.sh
    - stage: deploy
      script:
        - cargo doc --no-deps
        - echo "<meta http-equiv=refresh content=0;url=rubble/index.html>" > target/$TARGET_BUILD/doc/index.html
        - sudo pip install ghp-import
        - ghp-import -n target/$TARGET_BUILD/doc
        - git push -qf https://${GH_TOKEN}@github.com/jonas-schievink/rubble.git gh-pages

notifications:
  email:
    on_success: never
