[workspace]
members = [
    "rubble",
    "rubble-nrf5x",
    "rubble-docs",
    "demos/*/",
]

[profile.dev]
opt-level = "s"

[profile.release]
opt-level = "s"
debug = true
lto = true
codegen-units = 1
